language: node_js
node_js:
  - 12
  - 10
  - 8
install:
  - yarn
  - npm add -g codecov
jobs:
  include:
    - stage: test
      script: bash ./scripts/test.sh
    - stage: deploy
      if: branch = master
      script: bash ./scripts/deploy.sh
